// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jiiT_zV-EqsWHbpHp2uJ3V6x1A7r4yo',
    appId: '1:507613589987:web:384d37b63f6eb22eb530d6',
    messagingSenderId: '507613589987',
    projectId: 'local-talent-342112',
    authDomain: 'local-talent-342112.firebaseapp.com',
    storageBucket: 'local-talent-342112.appspot.com',
    measurementId: 'G-Y6NECXKWK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDini29AHvT0CHUG4l7NCYyRTdi-Io5Iu8',
    appId: '1:507613589987:android:33a90ec872e8cb77b530d6',
    messagingSenderId: '507613589987',
    projectId: 'local-talent-342112',
    storageBucket: 'local-talent-342112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4Jb3CIdyYR8M9dQ5wTBBRhCMYMxdFAg',
    appId: '1:507613589987:ios:327a12a26970f6f4b530d6',
    messagingSenderId: '507613589987',
    projectId: 'local-talent-342112',
    storageBucket: 'local-talent-342112.appspot.com',
    iosClientId: '507613589987-r4t5vgv3s05rv0l83lbd46vdjgv58vba.apps.googleusercontent.com',
    iosBundleId: 'com.swastha.swastha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4Jb3CIdyYR8M9dQ5wTBBRhCMYMxdFAg',
    appId: '1:507613589987:ios:327a12a26970f6f4b530d6',
    messagingSenderId: '507613589987',
    projectId: 'local-talent-342112',
    storageBucket: 'local-talent-342112.appspot.com',
    iosClientId: '507613589987-r4t5vgv3s05rv0l83lbd46vdjgv58vba.apps.googleusercontent.com',
    iosBundleId: 'com.swastha.swastha',
  );
}
